//categories
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const LOAD_CATEGORY = 'LOAD_CATEGORY'
export const EIDT_CATEGORY_REQUEST = 'EIDT_CATEGORY_REQUEST'
export const EDIT_CATEGORY_SUCCESS ='EDIT_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const SAVE_CATEGORY = 'SAVE_CATEGORY'
export const LOAD_CATEGORIES_REQUEST = 'LOAD_CATEGORIES_REQUEST'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL'
export const LOAD_CATEGORY_REQUEST = 'LOAD_CATEGORY_REQUEST'
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS'
export const LOAD_CATEGORY_FAIL = 'LOAD_CATEGORY_FAIL'
//session
export const LOGOUT = 'LOGOUT'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
//product
export const CREATE_PRODUCT_REQUEST = `CREATE_PRODUCT_REQUEST`
export const CREATE_PRODUCT_SUCCESS = `CREATE_PRODUCT_SUCCESS`
export const DELETE_PRODUCT_REQUEST ='DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const LOAD_PRODUCT_REQUEST = "LOAD_PRODUCT_REQUEST"
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS'
export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL'
export const SAVE_PRODUCT_TO_CART = 'SAVE_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART'
export const REMOVE_ALL_PRODUCT_TO_CART = 'REMOVE_ALL_PRODUCT_TO_CART'
export const GET_PRODUCT_TO_CART = 'GET_PRODUCT_TO_CART'
//bill
export const LOAD_BILLS_REQUEST = 'LOAD_BILLS_REQUEST'
export const LOAD_BILLS_SUCCESS = 'LOAD_BILLS_SUCCESS'
export const SAVE_BILLS = 'SAVE_BILLS'
export const CREATE_BILL_REQUEST = 'CREATE_BILL_REQUEST'
export const CREATE_BILL_SUCCESS = 'CREATE_BILL_SUCCESS'
export const GET_BILL_BY_USER_ID="GET_BILL_BY_USER_ID"
export const GET_ALL_BILL="GET_ALL_BILL"
export const LOAD_BILL_REQUEST ='LOAD_BILL_REQUEST'
export const LOAD_BILL_SUCCESS = 'LOAD_BILL_SUCCESS'
export const LOAD_BILLS_REQUEST_STATUS ='LOAD_BILLS_REQUEST_STATUS'
export const LOAD_BILLS_SUCCESS_STATUS = 'LOAD_BILLS_SUCCESS_STATUS'
export const REQUEST_CHANGE_STATUS_BILL_TO_DONE = 'REQUEST_CHANGE_STATUS_BILL_TO_DONE'
export const SUCCESS_CHANGE_STATUS_BILL_TO_DONE = 'SUCCESS_CHANGE_STATUS_BILL_TO_DONE'
//user
export const LOAD_USERS_REQUEST ='LOAD_USERS_REQUEST'
export const LOAD_USERS_SUCCESS ='LOAD_USERS_SUCCESS'

//list
export const LOAD_LIST_REQUEST = 'LOAD_LIST_REQUEST'
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS'
//gallery
export const UPLOAD_GALLERY_REQUEST = 'UPLOAD_GALLERY_REQUEST'
export const UPLOAD_GALLERY_SUCCES = 'UPLOAD_GALLERY_SUCCES'
